jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    before_install: cd mini-neptun-server
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: fYTYW5j3iPwK5d3yohNTawMQQhpOl+tP0L65PRF1/qDCcXQLI0vtDyrmJ9jePkWqaUAN7o0gZpq+PPxwIJbCr4Q2WVKlxr8kuS23MWl2i7pfWqwPbM08ps9hYhuIhtwKmV+7MJ5Q0OlVjcGVEp6VuxglV0njsZhm+H35w7rz8dHKWoAVX6R3wsW4yfJ0aH0E1c09x6Xe4/1vbn2STxH0dPYJsfAcWtjMAOf8Y3zBivLLWPDByKdspvm5yTBpxuRiksfxEFJ+oezJa/pbIwAezouLdX6TawXIizmx+P4Df7QrsqWn6l8caYmeTTvHZk/ULhFWcp+1w2sZxB9U2/AP70cvJNhOz3rPn6Fj7fVHK0pvDyLiBC/3v0AhBjHXS/2JVhtyLxqjANdtYTtCkFpQOkDFokZ39zZNSI5Xbg3QIWSbySfH7a2S3b6vkGFbsagbJwhOTUzoaXzeC+GR6sWQwAkSPcizhpdf0+ETrO4bBgLYItLos6TfRqBn2G50IbBAb/M6mUE05SgpA8AOSekIn+rzkE5yQLvHZre2eNUnq+SXzV6RYzXVc18D8ICXUMdP2R29R6/d/ErM6llg3SefoTmBCV9WwaeSxZEGLOIr5oCZ5eFG3GRqzM6CNMUAMIu6Hd5Ou/OfrXvrtf5EdhYaWD3eHYKAnDCyOkWVqkxDmhg=
      app: mini-neptun-server
      on: main
deploy:
  api_key:
    secure: T1Lr2P84hO9xK2bEmbYtkYfvauVmKWv05ZqmwrHr2YxN4D4X6eu3uYaGuEAZqhXeFC8Gdw12ZSJfsODvOGoeWNgy79qczHPeqLnrOcIgGbIYGNZblO2gLphFmC7flyH4/jzhJp4qdXkjxAMjeIg20UI8jSD/8x7BgH7e0s7QeeI+g8JEvUOqHx0tmKXWrhNC+c2FZ5NtBmr41DRcYrkkxLPPhvZ0mYj5qpY3TimIoRmHB4RCaeJvTMvVZai3l7sPNTzr1kc0dR2BBCMV81h3xTAb2jWbYWtvM+lc8SLbvdjQ711xysnVCg/Cq41j2AjqRz+UdEtdpWHurUsU96cFfgALkW2qEjh8zTUsoHWmsR/SnmmwVP1j/WPZ4udiHkY/KyosAgm7pSG77zPuoHppWgz1sJwKRHfnB+DUM1XF1Sw5w3/4f3USWtk+EJEX3w+oiWnsqeQNi5Uuo9MePVnKfZrYuTW/XCONwa6EX2GodVWd0r/6P2IcfzQbDQ8HQAWl1B1osZ6zjEbCSTip0kRlf7ebJc4sDyUJgXTGn9E4RIjOUm1yR+SRNb+FO25jcyoFYLx8WkdZ6glN2bGJD4JQFy9K8/MMrVgdezhIIqXyDkCoCVf5/NngntTUbRBg8SMzRQeBu4thza0Vpqj6z8zLaNGXLuVisoP4p3HGngp48iE=
