jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    before_install: cd mini-neptun-server
    before_script:
      - npm install -g @angular/cli
    script:
      - echo "npm test temporarily disabled"
    install: true
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key: XDvDK1zwXga0jGMPesHml4O4z/YUsDvb/mTId753uSLE1Q6KYHldSZc1dcVm9wSgNYcQ8eEzzXMzTjYoARMFg6Nqg42ruCM08HPmRGzvm7ltpgmoyIX7QYLUiLQzKhOyyXSmxNmbtX+QQZRTE/MOdAaACw4CjJmGGtULsWXfs+/3fqxiVH89u78clzOnhZ7fkm3xQWpaogXjld4wLhd2hrbCpBMzpms6i7xyAsxsgZy7wzcJTlvPoZjUG2J97hQ0uI2TE233W+R6fx9FBkmDVoGPi6N6YZJuAyTYxlBXbjqL5uYT0Ij1eKKuW+hkTYVkwO4NO+p7LPVmLJ25OdpQeIVsj9/zgPD0HV57MhGj1Ozr5WRTtw258wnsvBiQ+bh4T636YTQIyHyQw2cullVD9SYGXwaYIeLqjNRl9IRIgK1Sgr5Or/9r3qvCVTPyNnToLUEmQymJipJk7AJprpQVd96svAkWhcKdownWEbW5jYyYRUwTn2JLYz8D9i2gcXKIpjk2AuZsXqCgzX+BZX84GBZx4kQHuTAP44ohrDcOvtGzK1U1+xuGj0rywBCwrXw/RGLWsIBKd/W0WcdkSu1ZdLoMCuIgvpMo4eMLu3IaJ78XgDN9oOgSN49hyp5MIOGoRnMuDUb0J6xkteYykfmbGFYc1gJza82btlJ0J9Wl0fg=
      app: mini-neptun-server
      on: main
      repo: bdavid6/fullstackwp
