jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    before_install: cd mini-neptun-server
    before_script:
      - npm install -g @angular/cli
    script:
      - echo "npm test temporarily disabled"
    install: true
    after_success: npm run build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "NAx1jGH93aZYdSmQuhD+EcazZYlU7U/56eBtqafVCsexwxVHwS/itgpIieFBzonjt7T6lLa9+zLLyyiif49b2ZdOtB94Dpf0Bxt3rtBkvZHOlNrqSmL35CknqoJ4EcfGO+EVsRgUaG/HWpclNgETqis8pYJ6n5AaX4F+d1M8NTw21hE1UtHnJ+SQqSSJYxR/bxERnmzyQsSWukbN7nR/kGwkHguhbG2AjjhMm86XVmYU9C5kVC5ZnRcfVSUgKi4gJyUwGW5mTSmCG0vgkZPnXVjbIxBej9erT1K/0HuJRWKmmE7/8zo1ihiBKKHs8zBHV8pjRC8hg/bcFAPdEcUICxNTZlyEVmeHkPAX7SSHHvWhSqhhQhBi++QQnnIsjhBnYqNC/9BCzurgvpSFcnEVyZxAqctc3FpS6mHM+JDML8UT2m4tT6x4SDE7We+szEv/xLiI3n5dBDVNPNnvl+yylmk1qvndx6psksCuH1B9SskQLK+ilGF6D4NggL99QtLwB6XYE/kCqNd9G4U1tKSb4NTKSN3iVOHAhOtSP2dybH6oCAH9QHyUzdGvZjCEluzZGs0cFvjhHRI+mDRnjHTKvZiLIB4pvjtwK7lSgyf89xr5VEvw8KyVyjSQ71XLi+VRn7vhRG2iVhELNMZFM96VsGXSewBCsdvlaCEyOTg95sw="
      app: mini-neptun-server
      on: main
